### ISSUE TITLE
How to translate api administrator panel

### ISSUE THREAD

**Issue by luoyuu77** [justkeepquiet/tera-api#2]
Panel translation files in src will automatically generate overrides even if they are translated manually. How do you translate them

**Comment by justkeepquiet** [comment]
You need to copy the "en.json" file as a file for your language ("fr.json" for example) and then translate it. Only values need to be translated, the keys must remain original (see the "ru.json" file for an example).

**Comment by luoyuu77** [comment]
Thank you. That's what I did before, because the translated json format is incorrect

**Comment by justkeepquiet** [comment]
Try to use editor with code syntax check, like this https://code.visualstudio.com
