### ISSUE TITLE
SyntaxError: Unexpected token '.'

### ISSUE THREAD

**Issue by Diggers01** [justkeepquiet/tera-api#4]
Hi, I am getting an error from the logger.js file.
Below is an image of the issue I get:

![image](https://github.com/justkeepquiet/tera-api/assets/9864807/3fc5590c-ea86-4ffc-bf1c-59fe67ffd69f)

I tried running tera-api.bat file but it opens then closes. Then I tried to run the file in CMD and also use the command : `node src/app` but I get the same error. I am therefor not able to understand where the original error is coming from. Thanks.

**Comment by justkeepquiet** [comment]
Hi. Make sure you have the latest version of NodeJS installed. For the project to work, a version of at least v18.1.0 is required.

**Comment by Diggers01** [comment]
Hi yes thanks, that was the issue. I had node 12.
